disabled_rules:
  - cyclomatic_complexity
  - force_cast
  - function_body_length
  - type_body_length
  - file_length
  - identifier_name

opt_in_rules:
  - closure_end_indentation
  - indentation_width
  - implicit_return
  - literal_expression_end_indentation
  - modifier_order
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - multiple_closures_with_trailing_closure
  - multiline_arguments_brackets
  - multiline_arguments 
  - vertical_parameter_alignment_on_call

excluded: 
  - Pods
  - Eatery/API.swift
  - Eatery Watch App Extension/API.swift
